import React from 'react'
import { test, expect } from '@playwright/experimental-ct-react'
import OtherProfitLossPage from '../src/app/(app)/other-profit-loss/page'

async function setup(page: { evaluate: (fn: (owner: boolean) => void, arg: boolean) => Promise<void> }, owner = true) {
  await page.evaluate(owner => {
    Object.assign(window, { accountsCanEdit: owner, otherView: true, otherError: '', otherWrites: [], otherEntries: [
      { id: 'one', entry_date: '2026-10-09', kind: 'income', description: '<script>literal text</script>', category: 'Other sales', amount: '100.10' },
      { id: 'two', entry_date: '2026-10-10', kind: 'expense', description: 'Manual supplies', category: null, amount: '30.20' },
      { id: 'three', entry_date: '2026-09-01', kind: 'income', description: 'September sale', category: null, amount: '200.00' },
    ] })
  }, owner)
}

test('income and expense CRUD, filters and literal text', async ({ mount, page }) => {
  await setup(page)
  const component = await mount(<OtherProfitLossPage />)
  await component.getByLabel('Year', { exact: true }).selectOption('2026')
  await component.getByLabel('Month', { exact: true }).selectOption('10')
  await expect(component.getByText('RM 69.90', { exact: true })).toBeVisible()
  await expect(component.getByText('<script>literal text</script>', { exact: true })).toBeVisible()
  await component.getByRole('button', { name: 'Add Income', exact: true }).click()
  await page.getByLabel('Description', { exact: true }).fill('New manual sale')
  await page.getByLabel('Amount (RM)', { exact: true }).fill('0')
  await page.getByRole('button', { name: 'Save Entry' }).click()
  await expect(page.getByRole('alert')).toContainText('positive amount')
  await page.getByLabel('Amount (RM)', { exact: true }).fill('50.25')
  await page.getByLabel('Date', { exact: true }).fill('2026-10-11')
  await page.getByRole('button', { name: 'Save Entry' }).click()
  await expect(component.getByText('New manual sale', { exact: true })).toBeVisible()
  await component.getByRole('button', { name: 'Edit New manual sale', exact: true }).click()
  await page.getByLabel('Amount (RM)', { exact: true }).fill('60.25')
  await page.getByRole('button', { name: 'Save Entry' }).click()
  await expect(component.getByText('RM 60.25', { exact: true })).toBeVisible()
  await component.getByRole('button', { name: 'Delete New manual sale', exact: true }).click()
  await page.getByRole('button', { name: 'Delete Entry', exact: true }).click()
  await expect(component.getByText('New manual sale', { exact: true })).toHaveCount(0)
  await component.getByRole('button', { name: 'Add Expense', exact: true }).click()
  await page.getByLabel('Description', { exact: true }).fill('Independent expense')
  await page.getByLabel('Day of month', { exact: true }).fill('12')
  await page.getByLabel('Amount per month (RM)', { exact: true }).fill('100')
  await page.getByRole('button', { name: 'Save Entry' }).click()
  await expect(component.getByText('Net Loss', { exact: true })).toBeVisible()
  await expect(component.getByText('RM -30.10', { exact: true })).toBeVisible()
  await component.getByLabel('Month', { exact: true }).selectOption('all')
  await expect(component.getByText('September sale', { exact: true })).toBeVisible()
  await component.getByLabel('From date').fill('2026-10-10')
  await component.getByLabel('To date').fill('2026-10-10')
  await expect(component.getByText('No income for this period.')).toBeVisible()
  await expect(component.getByText('RM -30.20', { exact: true })).toBeVisible()
})

test('granted viewer cannot edit and mobile layout fits', async ({ mount, page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await setup(page, false)
  const component = await mount(<OtherProfitLossPage />)
  await component.getByLabel('Year', { exact: true }).selectOption('2026')
  await component.getByLabel('Month', { exact: true }).selectOption('10')
  await expect(component.getByText('RM 69.90', { exact: true })).toBeVisible()
  await expect(component.getByRole('button', { name: /Add Income|Add Expense|Edit |Delete / })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/Users/canggih/.openclaw/workspace/main/output/other-pl-monthly-20261009/mobile.png', fullPage: true })
})

test('denied page makes no ledger visible', async ({ mount, page }) => {
  await setup(page, false)
  await page.evaluate(() => Object.assign(window, { otherView: false }))
  const component = await mount(<OtherProfitLossPage />)
  await expect(page.getByRole('alert')).toContainText('do not have access')
  await expect(component.getByText('RM 69.90', { exact: true })).toHaveCount(0)
})

test('load and mutation failures remain visible and retryable', async ({ mount, page }) => {
  await setup(page)
  await page.evaluate(() => Object.assign(window, { otherError: 'Synthetic permission denied' }))
  const component = await mount(<OtherProfitLossPage />)
  await expect(component.getByRole('alert')).toContainText('Synthetic permission denied')
  await page.evaluate(() => Object.assign(window, { otherError: '' }))
  await component.getByRole('button', { name: 'Retry' }).click()
  await component.getByRole('button', { name: 'Add Expense', exact: true }).click()
  await page.getByLabel('Day of month', { exact: true }).fill('9')
  await page.getByLabel('Description', { exact: true }).fill('Failed expense')
  await page.getByLabel('Amount per month (RM)', { exact: true }).fill('10')
  await page.evaluate(() => Object.assign(window, { otherError: 'Synthetic write denied' }))
  await page.getByRole('button', { name: 'Save Entry' }).click()
  await expect(page.getByRole('alert')).toContainText('Synthetic write denied')
  await expect(page.getByRole('button', { name: 'Save Entry' })).toBeEnabled()
})

test('full-year totals include more than the API page size', async ({ mount, page }) => {
  await setup(page)
  await page.evaluate(() => Object.assign(window, { otherEntries: Array.from({ length: 501 }, (_, index) => ({ id: String(index), entry_date: '2026-10-09', kind: 'income', description: `Sale ${index}`, category: null, amount: '1.00' })) }))
  const component = await mount(<OtherProfitLossPage />)
  await component.getByLabel('Year', { exact: true }).selectOption('2026')
  await component.getByLabel('Month', { exact: true }).selectOption('all')
  await expect(component.getByText('RM 501.00', { exact: true }).first()).toBeVisible()
})

test('desktop review screenshot', async ({ mount, page }) => {
  await page.setViewportSize({ width: 1280, height: 900 })
  await setup(page)
  const component = await mount(<OtherProfitLossPage />)
  await component.getByLabel('Year', { exact: true }).selectOption('2026')
  await component.getByLabel('Month', { exact: true }).selectOption('10')
  await expect(component.getByText('RM 69.90', { exact: true })).toBeVisible()
  await page.screenshot({ path: '/Users/canggih/.openclaw/workspace/main/output/other-pl-monthly-20261009/desktop.png', fullPage: true })
})


test('multi-month per-month preview, totals, single-row edit/delete and leap-day dates', async ({ mount, page }) => {
  await setup(page)
  const component = await mount(<OtherProfitLossPage />)
  await component.getByLabel('Year', { exact: true }).selectOption('2026')
  await component.getByRole('tab', { name: 'Jan', exact: true }).click()
  await component.getByRole('button', { name: 'Add Expense', exact: true }).click()
  await page.getByLabel('Expense Feb', { exact: true }).check()
  await page.getByLabel('Expense Mar', { exact: true }).check()
  await page.getByLabel('Day of month').fill('31')
  await page.getByLabel('Description', { exact: true }).fill('Rental')
  await page.getByLabel('Amount per month (RM)', { exact: true }).fill('1000')
  await expect(page.getByRole('status')).toContainText('3 months × RM 1,000.00 per month = RM 3,000.00 total')
  await expect(page.getByText(/Shorter months use/)).toContainText('2026-01-31, 2026-02-28, 2026-03-31')
  await page.getByRole('button', { name: 'Save Entry' }).scrollIntoViewIfNeeded()
  await expect(page.getByRole('button', { name: 'Save Entry' })).toBeVisible()
  await page.screenshot({ path: '/Users/canggih/.openclaw/workspace/main/output/other-pl-monthly-20261009/expense-desktop.png' })
  await page.getByRole('button', { name: 'Save Entry' }).click()
  await expect(component.getByRole('tab', { name: 'Overall', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(component.getByText('Rental', { exact: true })).toHaveCount(3)
  await expect(component.getByText('RM 3,030.20', { exact: true }).first()).toBeVisible()
  expect(await page.evaluate(() => (window as unknown as { otherWrites: unknown[] }).otherWrites.length)).toBe(1)
  await page.screenshot({ path: '/Users/canggih/.openclaw/workspace/main/output/other-pl-monthly-20261009/overall-desktop.png', fullPage: true })
  for (const month of ['Jan', 'Feb', 'Mar']) {
    await component.getByRole('tab', { name: month, exact: true }).click()
    await expect(component.getByText('Rental', { exact: true })).toHaveCount(1)
    await expect(component.getByText('RM -1,000.00', { exact: true })).toBeVisible()
  }
  await component.getByRole('tab', { name: 'Feb', exact: true }).click()
  await component.getByRole('button', { name: 'Edit Rental', exact: true }).click()
  await expect(page.getByLabel('Expense Jan', { exact: true })).toHaveCount(0)
  await page.getByLabel('Amount (RM)', { exact: true }).fill('1100')
  await page.getByRole('button', { name: 'Save Entry' }).click()
  await component.getByRole('button', { name: 'Delete Rental', exact: true }).click()
  await page.getByRole('button', { name: 'Delete Entry', exact: true }).click()
  await component.getByRole('tab', { name: 'Overall', exact: true }).click()
  await expect(component.getByText('Rental', { exact: true })).toHaveCount(2)
  await component.getByLabel('Year', { exact: true }).selectOption('2024')
  await component.getByRole('tab', { name: 'Feb', exact: true }).click()
  await component.getByRole('button', { name: 'Add Expense', exact: true }).click()
  await page.getByLabel('Day of month').fill('31')
  await expect(page.getByText(/Shorter months use/)).toContainText('2024-02-29')
  await page.getByLabel('Description', { exact: true }).fill('Leap rental')
  await page.getByLabel('Amount per month (RM)', { exact: true }).fill('0.10')
  await page.getByRole('button', { name: 'Save Entry' }).click()
  await expect(component.getByText('2024-02-29', { exact: true })).toBeVisible()
  await component.getByLabel('Year', { exact: true }).selectOption('2026')
  await expect(component.getByText('Leap rental', { exact: true })).toHaveCount(0)
})

test('empty selection and failed multi-month insert write no entries; retry succeeds', async ({ mount, page }) => {
  await setup(page)
  const component = await mount(<OtherProfitLossPage />)
  await component.getByLabel('Year', { exact: true }).selectOption('2026')
  await component.getByRole('tab', { name: 'Jan', exact: true }).click()
  await component.getByRole('button', { name: 'Add Expense', exact: true }).click()
  await page.getByLabel('Description', { exact: true }).fill('Batch rental')
  await page.getByLabel('Amount per month (RM)', { exact: true }).fill('1000')
  await page.getByLabel('Expense Jan', { exact: true }).uncheck()
  await page.getByRole('button', { name: 'Save Entry' }).click()
  await expect(page.getByRole('alert')).toContainText('Choose at least one month')
  await page.getByLabel('Expense Jan', { exact: true }).check()
  await page.getByLabel('Expense Dec', { exact: true }).check()
  await page.evaluate(() => Object.assign(window, { otherError: 'Synthetic batch denied' }))
  await page.getByRole('button', { name: 'Save Entry' }).click()
  await expect(page.getByRole('alert')).toContainText('Synthetic batch denied')
  expect(await page.evaluate(() => (window as unknown as { otherEntries: unknown[] }).otherEntries.length)).toBe(3)
  await page.evaluate(() => Object.assign(window, { otherError: '' }))
  await page.getByRole('button', { name: 'Save Entry' }).click()
  await expect(component.getByText('Batch rental', { exact: true })).toHaveCount(2)
})

test('mobile owner can select months and see total without document overflow', async ({ mount, page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await setup(page)
  const component = await mount(<OtherProfitLossPage />)
  await component.getByLabel('Year', { exact: true }).selectOption('2026')
  await component.getByRole('tab', { name: 'Jan', exact: true }).click()
  await component.getByRole('button', { name: 'Add Expense', exact: true }).click()
  await page.getByLabel('Expense Feb', { exact: true }).check()
  await page.getByLabel('Expense Mar', { exact: true }).check()
  await page.getByLabel('Description', { exact: true }).fill('Rental')
  await page.getByLabel('Amount per month (RM)', { exact: true }).fill('1000')
  await expect(page.getByRole('status')).toContainText('RM 3,000.00 total')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Save Entry' }).scrollIntoViewIfNeeded()
  await expect(page.getByRole('button', { name: 'Save Entry' })).toBeVisible()
  await page.screenshot({ path: '/Users/canggih/.openclaw/workspace/main/output/other-pl-monthly-20261009/expense-mobile.png' })
  await page.getByRole('button', { name: 'Save Entry' }).click()
  await expect(component.getByRole('tab', { name: 'Overall', exact: true })).toHaveAttribute('aria-selected', 'true')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/Users/canggih/.openclaw/workspace/main/output/other-pl-monthly-20261009/overall-mobile.png', fullPage: true })
  await component.getByRole('tab', { name: 'Overall', exact: true }).focus()
  await page.keyboard.press('End')
  await expect(component.getByRole('tab', { name: 'Dec', exact: true })).toHaveAttribute('aria-selected', 'true')
  await component.getByRole('tab', { name: 'Jan', exact: true }).click()
  const expenseTable = component.getByLabel('Expenses entries table', { exact: true })
  await expenseTable.evaluate(element => { element.scrollLeft = element.scrollWidth })
  await component.getByRole('button', { name: 'Edit Rental', exact: true }).click()
  await expect(page.getByLabel('Amount (RM)', { exact: true })).toHaveValue('1000')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
})

for (const owner of [true, false]) {
  test(`invoice toggle persists across periods and remount; owner=${owner}`, async ({ mount, page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await setup(page, owner)
    let component = await mount(<OtherProfitLossPage />)
    await component.getByLabel('Year', { exact: true }).selectOption('2026')
    const flag = component.getByRole('button', { name: 'No invoice for Manual supplies', exact: true })
    await expect(flag).toHaveAttribute('aria-pressed', 'false')
    await expect(component.getByRole('button', { name: /No invoice for/ })).toHaveCount(1)
    await flag.click()
    await expect(flag).toHaveAttribute('aria-pressed', 'true')
    await expect(flag).toBeEnabled()
    await page.screenshot({ path: `/Users/canggih/.openclaw/workspace/main/output/other-pl-invoice-20261009/flagged-${owner ? 'owner' : 'accountant'}-mobile.png`, fullPage: true })
    await component.getByRole('tab', { name: 'Oct', exact: true }).click()
    await expect(flag).toHaveAttribute('aria-pressed', 'true')
    await component.unmount()
    component = await mount(<OtherProfitLossPage />)
    await component.getByLabel('Year', { exact: true }).selectOption('2026')
    const reloaded = component.getByRole('button', { name: 'No invoice for Manual supplies', exact: true })
    await expect(reloaded).toHaveAttribute('aria-pressed', 'true')
    await page.evaluate(() => Object.assign(window, { otherError: 'Synthetic invoice denied' }))
    await reloaded.click()
    await expect(component.getByRole('alert')).toContainText('Synthetic invoice denied')
    await expect(reloaded).toHaveAttribute('aria-pressed', 'true')
    await expect(reloaded).toBeEnabled()
    await page.evaluate(() => Object.assign(window, { otherError: '' }))
    await reloaded.focus()
    await page.keyboard.press('Space')
    await expect(reloaded).toHaveAttribute('aria-pressed', 'false')
    await expect(reloaded).toBeEnabled()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await expect(component.getByText('RM 30.20', { exact: true }).first()).toBeVisible()
    await page.screenshot({ path: `/Users/canggih/.openclaw/workspace/main/output/other-pl-invoice-20261009/toggle-${owner ? 'owner' : 'accountant'}-mobile.png`, fullPage: true })
  })
}
